openapi: 3.0.0
servers:
  - description: Prod server
    url: 'https://api.eigensonne.de/finanzierung-api/v1'
  - description: Dev server
    url: 'https://api-local.eigensonne.de/finanzierung-api/v1'
security:
  - HTTPBearer: []
info:
  version: 1.0.0
  title: EIGENSONNE's Finanzierung API
  description: >-
    An API for finanzierung partners to inform us about statuses of our
    contracts with them
  contact:
    email: thao.lipasti@eigensonne.de
paths:
  /api/login_check:
    $ref: paths/api@login_check.yaml
  /contracts/credit_check:
    $ref: paths/contracts@credit_check.yaml
  /contracts/land_registry_check:
    $ref: paths/contracts@land_registry_check.yaml
components:
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
      bearerFormat: JWT