openapi: 3.0.0
servers:
  - description: Prod server
    url: https://api.eigensonne.de/finanzierung-api/v1
  - description: Dev server
    url: https://api-local.eigensonne.de/finanzierung-api/v1
security:
  - bearerAuth: []
info:
  version: 1.0.0
  title: EIGENSONNE's Finanzierung API
  description: >-
    an API for finanzierung partners to inform us about statuses of our
    contracts with them
  contact:
    email: thao.lipasti@eigensonne.de
paths:
  /contracts/credit_check:
    post:
      tags:
        - checks
      description: updating the result of credit check
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                contract_id:
                  type: string
                  example: e0c411c8-ba8e-425d-a313-eaeade5be468
                outcome:
                  type: string
                  enum:
                    - Passed
                    - Failed
                    - Pending
                    - Unknown
      responses:
        '204':
          description: success
        '404':
          description: contract not found or not yet reviewed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_message:
                    type: string
                    example: Contract not found
  /contracts/land_registry_check:
    post:
      tags:
        - checks
      description: Updating the result of land registry check
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                contract_id:
                  type: string
                  example: e0c411c8-ba8e-425d-a313-eaeade5be468
                outcome:
                  type: string
                  enum:
                    - Passed
                    - Failed
                    - Pending
                    - Unknown
      responses:
        '204':
          description: success
        '404':
          description: contract not found or not yet reviewed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_message:
                    type: string
                    example: Contract not found
components: {}
